INSERT INTO ELETRODOMESTICO (ID_ENDERECO,BAIRRO ,CIDADE ,ESTADO ,MARCA ,NOME ,NUMERO ,RUA ,TENSAO )VALUES(111,'Cajueiro', 'Marica', 'RJ','Consul','Geladeira',47,'Cajueiros',127);
INSERT INTO ELETRODOMESTICO (ID_ENDERECO,BAIRRO ,CIDADE ,ESTADO ,MARCA ,NOME ,NUMERO ,RUA ,TENSAO )VALUES(222,'Conquista', 'Marica', 'MG','Eletrolux','Liquidificador',47,'Andiroba',320);
INSERT INTO ELETRODOMESTICO (ID_ENDERECO,BAIRRO ,CIDADE ,ESTADO ,MARCA ,NOME ,NUMERO ,RUA ,TENSAO )VALUES(333,'Morada do Sol', 'Marica', 'BA','Asus','Notebook',47,'Antunes',120);
INSERT INTO ELETRODOMESTICO (ID_ENDERECO,BAIRRO ,CIDADE ,ESTADO ,MARCA ,NOME ,NUMERO ,RUA ,TENSAO )VALUES(444,'Trindade', 'Marica', 'SC','Dell','Computador',47,'Abacate',127);
INSERT INTO ELETRODOMESTICO (ID_ENDERECO,BAIRRO ,CIDADE ,ESTADO ,MARCA ,NOME ,NUMERO ,RUA ,TENSAO )VALUES(555,'Centro', 'Marica', 'PR','Black-Deck','Ventilador',47,'Banana',127);
INSERT INTO ELETRODOMESTICO (ID_ENDERECO,BAIRRO ,CIDADE ,ESTADO ,MARCA ,NOME ,NUMERO ,RUA ,TENSAO )VALUES(666,'Andiroba', 'Marica', 'AM','Arno','Ferro',47,'Uva',720);
INSERT INTO ELETRODOMESTICO (ID_ENDERECO,BAIRRO ,CIDADE ,ESTADO ,MARCA ,NOME ,NUMERO ,RUA ,TENSAO )VALUES(777,'Horto', 'Marica', 'AM','Philips','Microondas',47,'Ameixa',620);
INSERT INTO ELETRODOMESTICO (ID_ENDERECO,BAIRRO ,CIDADE ,ESTADO ,MARCA ,NOME ,NUMERO ,RUA ,TENSAO )VALUES(888,'Paz', 'Marica', 'ES','Brastemp','Frezzer',47,'Jiló',127);
INSERT INTO ELETRODOMESTICO (ID_ENDERECO,BAIRRO ,CIDADE ,ESTADO ,MARCA ,NOME ,NUMERO ,RUA ,TENSAO )VALUES(999,'Procon', 'Marica', 'SP','Dako','Fogão',47,'Abacate',220);